var wordList = [
    "BEETHOVEN",
    "MOZART",
    "BACH",
    "WAGNER",
    "HAYDN",
    "BRAHMS",
    "SCHUBERT",
    "TCHAIKOVSKY",
    "HANDEL",
    "STRAVINSKY",
    "SCHUMANN",
    "CHOPIN",
    "MENDELSSOHN",
    "LISZT",
    "DVORAK",
    "VERDI",
    "MAHLER",
    "VIVALDI",
    "STRAUSS",
    "PROKOFIEV",
    "SHOSTAKOVICH",
    "BERLIOZ",
    "BRUCKNER",
    "MONTEVERDI",
    "SIBELIUS",
    "RAVEL",
    "WILLIAMS",
    "MUSSORGSKY",
    "PUCCINI",
    "PURCELL",
    "ROSSINI",
    "ELGAR",
    "RACHMANINOFF"
]

module.exports = wordList;
